import type { Metadata } from 'next';
import "../globals.css";
import localFont from "next/font/local";

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

const vazir_font = localFont({
  src: "./../../../public/fonts/Vazirmatn-Regular.woff2",
  });

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" className={vazir_font.className}>
      <body>{children}</body>
    </html>
  );
}
